# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('blocked', models.BooleanField(default=False)),
                ('cash', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('code', models.IntegerField()),
                ('cash', models.IntegerField(default=0)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm_interface.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atm_interface.Person'),
        ),
    ]
