# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='card_id',
            new_name='card',
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
